version: '3'

services:
  app:
    image: fauria/vsftpd
    restart: always
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - SSL_ENABLE=${SSL_ENABLE}
      - TLS_CERT=${TLS_CERT}
      - TLS_KEY=${TLS_KEY}
      - PASV_ADDRESS=${PASV_ADDRESS}
      - PASV_MIN_PORT=${PASV_MIN_PORT}
      - PASV_MAX_PORT=${PASV_MAX_PORT}
    volumes:
      - ./volume/ftp-data:/home/vsftpd
      - ./volume/logs:/var/log/vsftpd
    networks:
      nginx_network:
        ipv4_address: 10.0.2.52

networks:
  nginx_network:
    external: true
